version: '2.1'

x-common_variables:
  &services_hosts
  REDIS_HOST: 182.20.0.3

services:
  phoenix:
    image: phoenix
    tty: true
    ports:
      - "4000:4000"
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        SSH_PUBLIC_KEY: ""
    environment:
      REDIS_HOST: 182.20.0.3
    volumes:
      - ./lib:/opt/app/lib
      - ./assets:/opt/app/assets
    command: iex -S mix
    networks:
      backend:
        ipv4_address: 182.20.0.2

  kv_store_1:
    image: redis:alpine
    environment: *services_hosts
    ports:
      - "6379:6379"
    networks:
      backend:
        ipv4_address: 182.20.0.3

networks:
  backend:
    ipam:
      config:
        - subnet: 182.20.0.0/24